### ISSUE TITLE
Test are failing due to a missing fixture

### ISSUE THREAD

**Issue by taganaka** [Gild/ruby-swagger#16]
```text
cp: /Users/francescolaurita/Development/ruby-swagger/spec/swagger/io/../../fixtures/doc/swagger/*: No such file or directory
F

Failures:

  1) Swagger::IO::FileSystem when loading data should generate a valid swagger document
     Failure/Error: doc = Swagger::IO::FileSystem.read
     Errno::ENOENT:
       No such file or directory @ rb_sysopen - /Users/francescolaurita/Development/ruby-swagger/spec/swagger/io/../../doc//base_doc.yml
     # ./lib/ruby-swagger/io/file_system.rb:71:in `read'
     # ./spec/swagger/io/file_system_spec.rb:79:in `block (3 levels) in <top (required)>'

  2) Swagger::IO::FileSystem when compiling data should generate a valid swagger document
     Failure/Error: Swagger::IO::FileSystem.new(Swagger::IO::FileSystem.read).compile!
     Errno::ENOENT:
       No such file or directory @ rb_sysopen - /Users/francescolaurita/Development/ruby-swagger/spec/swagger/io/../../doc//base_doc.yml
     # ./lib/ruby-swagger/io/file_system.rb:71:in `read'
     # ./spec/swagger/io/file_system_spec.rb:132:in `block (3 levels) in <top (required)>'

Finished in 0.97904 seconds (files took 0.73491 seconds to load)
164 examples, 2 failures

Failed examples:

rspec ./spec/swagger/io/file_system_spec.rb:78 # Swagger::IO::FileSystem when loading data should generate a valid swagger document
rspec ./spec/swagger/io/file_system_spec.rb:131 # Swagger::IO::FileSystem when compiling data should generate a valid swagger document
```

Looks like a doc directory has not been included into the main repository

cheers

**Comment by openmosix** [comment]
This should be solved. @taganaka can you confirm?

**Comment by taganaka** [comment]
:+1: 
Confirmed. tnx
